## Gaussian Naive Bayes Classifier

Gaussian Naive Bayes is a probabilistic classifier based on Bayes' theorem, which assumes that the features are independent given the class. It is particularly effective for classification tasks with continuous features.

In [ ]:
import pandas as pd

email_data = {"Email Size (KB)": [48.97, 14.59, 28.24, 32.62, 23.83, 14.30, 32.90, 51.14, 22.65, 27.71, 41.29, 22.67, 26.21, 9.26], 
              "Link Count": [2, 11, 1, 2, 1, 9, 3, 5, 2, 1, 4, 2, 1, 13], 
              "Unique Word Frequency (%)": [65.2, 22.1, 82.4, 79.8, 88.5, 18.4, 75.2, 61.9, 84.1, 81.3, 58.7, 86.4, 83.2, 15.6], 
              "Email Length (Chars)": [1240, 410, 850, 920, 710, 380, 980, 1310, 690, 820, 1150, 680, 790, 320],
              "Target": ["Promotion", "Spam", "Not Spam", "Not Spam", "Not Spam", 
                                  "Spam", "Not Spam", "Promotion", "Not Spam", "Not Spam", 
                                  "Promotion", "Not Spam", "Not Spam", "Spam"]}
df = pd.DataFrame(email_data)

In [ ]:
email_spam = df[df['Target'] == 'Spam']
email_notspam = df[df['Target'] == 'Not Spam']
email_promotion = df[df['Target'] == 'Promotion']

In [ ]:
def mean_and_variance(features_df):
  mean_series = features_df.mean()
  variance_series = features_df.var()
  df = pd.DataFrame({"Mean": mean_series, "Variance": variance_series})
  return df
  
features = ['Email Size (KB)', 'Link Count', 'Unique Word Frequency (%)', 'Email Length (Chars)']

In [ ]:
# Mean and variance for each features Spam
X_spam = email_spam[features]
y_spam = email_spam['Target']
mean_and_variance(X_spam)

                                 Mean     Variance
Email Size (KB)             12.716667     8.982433
Link Count                  11.000000     4.000000
Unique Word Frequency (%)   18.700000    10.630000
Email Length (Chars)       370.000000  2100.000000

In [ ]:
X_notspam = email_notspam[features]
y_notspam = email_notspam['Target']
mean_and_variance(X_notspam)

                                Mean      Variance
Email Size (KB)             27.10375     16.670627
Link Count                   1.62500      0.553571
Unique Word Frequency (%)   82.61250     16.598393
Email Length (Chars)       805.00000  12028.571429

In [ ]:
X_promotion = email_promotion[features]
y_promotion = email_promotion['Target']
mean_and_variance(X_promotion)

                                  Mean     Variance
Email Size (KB)              47.133333    26.785633
Link Count                    3.666667     2.333333
Unique Word Frequency (%)    61.933333    10.563333
Email Length (Chars)       1233.333333  6433.333333

In [ ]:
from scipy.stats import norm

# New input
new_data = [45.25, 4, 54.3, 1000]

In [ ]:
# Calculate PDF for Class Spam
pdf_spam = norm.pdf(new_data, X_spam.mean(), X_spam.std())
for i in range(len(pdf_spam)):
  print(f"P({features[i]}: {new_data[i]}| Spam) = {pdf_spam[i]}")

P(Email Size (KB): 45.25| Spam) = 3.446091340069849e-27
P(Link Count: 4| Spam) = 0.0004363413475228801
P(Unique Word Frequency (%): 54.3| Spam) = 1.5786991666158679e-27
P(Email Length (Chars): 1000| Spam) = 7.924500161558664e-44

In [ ]:
# Calculate PDF for Class Not Spam
pdf_notspam = norm.pdf(new_data, X_notspam.mean(), X_notspam.std())
for i in range(len(pdf_notspam)):
  print(f"P({features[i]}: {new_data[i]}| Not Spam) = {pdf_notspam[i]}")

P(Email Size (KB): 45.25| Not Spam) = 5.020366160604712e-06
P(Link Count: 4| Not Spam) = 0.00328622971510736
P(Unique Word Frequency (%): 54.3| Not Spam) = 3.191797155920671e-12
P(Email Length (Chars): 1000| Not Spam) = 0.0007487763645413117

In [ ]:
# Calculate PDF for Class Promotion
pdf_promotion = norm.pdf(new_data, X_promotion.mean(), X_promotion.std())
for i in range(len(pdf_promotion)):
  print(f"P({features[i]}: {new_data[i]}| Promotion) = {pdf_promotion[i]}")

P(Email Size (KB): 45.25| Promotion) = 0.07214471836332392
P(Link Count: 4| Promotion) = 0.2550241615316513
P(Unique Word Frequency (%): 54.3| Promotion) = 0.007784245607443229
P(Email Length (Chars): 1000| Promotion) = 7.227761551333146e-05